[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1028:Enum Storage should be Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1031:Do not catch general exception types")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1034:Nested types should not be visible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1062:Validate arguments of public methods")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1707:Identifiers should not contain underscores")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1710:Identifiers should have correct suffix")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1724:Type names should not match ")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance",   "CA1812:Avoid uninstantiated internal classes", Justification = "Reflection!")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance",   "CA1819:Properties should not return arrays")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2007:Consider calling ConfigureAwait on the awaited task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security",      "CA2100:Review SQL queries for security vulnerabilities")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0016:Use 'throw' expression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE1006:Naming Styles")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2200:Rethrow to preserve stack details.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2234:Pass system uri objects instead of strings")]
